app: surmon-me
stage: prod
component: http
name: surmon-me
org: '1253995560'

# https://github.com/serverless-components/tencent-http/blob/master/docs/configure.md
inputs:
  region: ap-hongkong
  type: web
  src:
    src: ./
    # dist: ./
    # hook: npm run build
    # hook: npm run build
    # dist: ./
    exclude:
      - 'node_modules/**'
  faas:
    runtime: Nodejs12.16
    framework: express
    name: '${name}'
    environments:
      - key: PORT
        value: 9000
    eip: true
    timeout: 3
    memorySize: 512
    tags: []
    layers:
      - name: '${output:${stage}:${app}:surmon-me-layer.name}'
        version: '${output:${stage}:${app}:surmon-me-layer.version}'

  # https://github.com/serverless-components/tencent-http/blob/master/docs/configure.md#apigw
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains:
      - domain: serverless.surmon.me
        certId: sGtdxO8A
        isForcedHttps: true
        protocols:
          - http
          - https
        pathMap:
          - path: /
            environment: release
        customMap: true
        isDefaultMapping: false

  # https://github.com/serverless-components/tencent-http/blob/master/docs/configure.md#source
  assets:
    cos:
      bucket: surmon-me-1253995560
      acl:
        permissions: public-read
      sources:
        - src: ./dist/client
          targetDir: /

  isAutoCiDeploy: false
