name: Deploy to server
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    name: Build test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch to master
      uses: actions/checkout@master
      with:
        ref: master
    - name: Run test
      uses: ./.github/actions/build-test
  deploy:
    name: Deploy to server
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Exec deploy script with SSH
        if: github.event.pull_request.merged == true
        uses: maddox/actions/ssh@master
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        with:
          args: sh /usr/local/wwwroot/surmon.me/.deploy/main.sh
