name: Deploy to server
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch to master
      uses: actions/checkout@master
    - name: Test
      uses: ./.github/workflows/build-test
  deploy:
    name: Deploy to server
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Exec deploy script with SSH
        uses: maddox/actions/ssh@master
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        with:
          args: sh /usr/local/wwwroot/surmon.me/.deploy/main.sh
